### ISSUE TITLE
PostGIS Java2D geometry implementation of points

### ISSUE THREAD

**Issue by laborgi** [postgis/postgis-java#27]
The PostGIS Java2D implementation of points as GeneralPath accordingly to the Javadoc is: "Points thus are translated into MoveTo() followed by a closePath."
I've tested various methods.The point is drawn when the GeneralPath has a lineTo() to the same coordinates instead closePath() (as described below: "Maybe we need a LineTo() to the same coordinages instead.")
Perhaps someone can correct it :-)
Thanks

**Comment by phillipross** [comment]
You mean to say that the documentation is incorrect.  This implementation is actually quite old... referring to java 1.5.  The note about adjacent MoveTo commands being thrown out is no longer applicable?

**Comment by laborgi** [comment]
Hallo Phillip,

I'm sorry, I do not understand exactly the content of your post, 
especially what you mean with "The note about adjacent MoveTo commands 
being thrown out is no longer applicable?".

At the moment it is not possible to draw geometry containing only 
points. So, my concern was to solve this problem.
This can be done by changing the line 158 in the class 
ShapeBinaryParser.java (method parsePoint()) from "path.closePath(...)" 
to  "path.lineTo(...)" with the coordinates of the starting point (from 
the line above) as parameter.
If this is changed, also points are drawn correctly by Java2D.

Best regards.
Ines


Am 16.07.2015 um 18:05 schrieb Phillip Ross:

**Comment by phillipross** [comment]
Sorry Ines, I think I understand what you mean now.  At first I thought you were saying that the documentation PGShapeGeometry was incorrect/inaccurate, and I was saying that it might be inaccurate because it was written when there might have been java2d rendering bugs in java 1.5.

But I guess what you are actually saying is that drawing points can now be done with moveTo()+lineTo() instead of moveTo()+closePath().  Is this correct?

Ideally we'd have some test code to illustrate this.  If you could provide some test code we'd be very grateful.  I'll see if I can produce a test case on my own that illustrates the problem.  It sounds like your fix is a simple code change, but we should have some test code in place that tests geometries that are only points along with geometries that are not exclusively points.

Thanks!

**Comment by phillipross** [comment]
Hi @laborgi... would you be able to review the [pull request](https://github.com/postgis/postgis-java/pull/28) I just submitted which provides a patch to the point parsing code?  Thanks!

**Comment by laborgi** [comment]
Hi Phillip,

I think the changed code works. Your test class and my own tests ran 
through without any problems.

Many Thanks!
Ines


Am 18.07.2015 um 23:27 schrieb Phillip Ross:

**Comment by phillipross** [comment]
Thanks Ines. I merged the pull request into the master branch.  I'll do one more run of manual testing on the java2d test (I'm not sure how to properly automate testing of this if it's even possible) and then close out this issue if everything is fine.
Thanks again!

**Comment by phillipross** [comment]
This issue has been verified via manual testing on master 518a9d7
