### ISSUE TITLE
PostGIS JDBC Driver extension inconsistencies

### ISSUE THREAD

**Issue by asifnaeem** [postgis/postgis-java#39]
While using postgis-2.1.8.tar.gz PostGIS JDBC extension with PG9.5 following anomalies are observed i.e.

1. Version.getFullVersion() method returning wrong version i.e.
> PostGIS JDBC V2.0.0
    It seems that related version information require to be updated i.e.
      java/jdbc/src/org/postgis/version.properties
>       REL_MAJOR_VERSION=2
>       REL_MINOR_VERSION=0
>       REL_MICRO_VERSION=0

2. Test case java/jdbc/src/examples/TestParser.java fail with two type of errors i.e.

A). There are # of failure because of "can not mix dimensionality in a geometry", It seems a test case bug.

>     2016-02-05 11:19:54 PKT ERROR:  can not mix dimensionality in a geometry
>     2016-02-05 11:19:54 PKT HINT:  "...IONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 52 within geometry
>     2016-02-05 11:19:54 PKT STATEMENT:  SELECT geometry_in('GEOMETRYCOLLECTIONM(POINT(10 10 20),POINT(20 20 20))')

             Test case output snippet i.e.

> Testing on connection 0: postgres
> --- Server side error: org.postgresql.util.PSQLException: ERROR: can not mix dimensionality in a geometry
>   Hint: "...ONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 53 within geometry
> SQLout  :  GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> Eq SQLout: yes
> Prepared:  GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> Eq Prep: yes
> --- Server side error: org.postgresql.util.PSQLException: ERROR: can not mix dimensionality in a geometry
>   Hint: "...ONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 53 within geometry
> --- Server side error: org.postgresql.util.PSQLException: ERROR: can not mix dimensionality in a geometry
>   Hint: "...ONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 53 within geometry
> hexNWKT:   GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> equal    : yes
> hexXWKT:   GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> equal    : yes
> NWKT:      GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> equal    : yes
> XWKT:      GEOMETRYCOLLECTIONM(POINTM(10 10 20),POINTM(20 20 20))
> equal    : yes

You can observe that test case is using POINT instead of POINTM for some cases that is troubling PostGIS.

 B). Second set of errors are failing with following errors i.e.

> 2016-02-05 11:19:55 PKT ERROR:  parse error - invalid geometry
> 2016-02-05 11:19:55 PKT HINT:  "GEOMETRYCOLLECTION(EMPTY" <-- parse error at position 24 within geometry
> 2016-02-05 11:19:55 PKT STATEMENT:  SELECT geometry_in('GEOMETRYCOLLECTION(EMPTY)')

It looks like a bug to me that result in query like "SELECT geometry_in('GEOMETRYCOLLECTION(EMPTY)')" instead of "SELECT geometry_in('GEOMETRYCOLLECTION EMPTY')" i.e. new representation.

I have also reported this issue on https://trac.osgeo.org/postgis/ticket/3453.

**Comment by phillipross** [comment]
@asifnaeem I'm looking into this report now, but just as a follow-up question, what environment(s) are you testing with?
Is this postgresql 9.5.0 w/ PostGIS 2.1.8?  or PostGIS 2.2.1?
And which version of the PostGIS JDBC extensions are you testing with?

**Comment by asifnaeem** [comment]
Thank you for looking into it. Issue is reproducible with PostgreSQL 9.5, PostGIS 2.1.8 with included PostGIS JDBC extensions (i.e. postgis-2.1.8.tar.gz/postgis/java/jdbc). Please do let me know if I missed something or more information is required. Thanks.

**Comment by phillipross** [comment]
If you are using a release that is bundled with debian, this could be a debian packaging issue.

Would you be able to try to download and use one of the releases from github or maven central?

If you want to build from source, you can download from [github](https://github.com/postgis/postgis-java/archive/v2.2.0.tar.gz).
If you just want a jar to include in your classpath, download from [maven central](http://search.maven.org/remotecontent?filepath=net/postgis/postgis-jdbc/2.2.0/postgis-jdbc-2.2.0.jar)

If these work for you, we'll have to work with the maintainer of the debian package to narrow down the problem.

**Comment by asifnaeem** [comment]
Thank you. I have built PostgreSQL, [PostGIS](http://download.osgeo.org/postgis/source/postgis-2.1.8.tar.gz) and [PostGIS JDBC extension](http://download.osgeo.org/postgis/source/postgis-2.1.8.tar.gz) from source. It seems that[ maven central](https://repo1.maven.org/maven2/net/postgis/postgis-jdbc/) don't have jar for latest stable version of PostGIS 2.1 i.e. 2.1.8. I am using PostGIS 2.1.8.

**Comment by Elbehery** [comment]
But the 2.2 just be supporting lower versions, is not it ? ..

I am just started using it, would like to know if there is an issue using v 2.2 !!

**Comment by asifnaeem** [comment]
Can't it be fixed in PostGIS 2.1 branch, related PostGIS JDBC extension is still part of it. These are failures observed while running related exmaple tests (java/jdbc/src/examples). Can I use [v2.1-maintenance](https://github.com/postgis/postgis-java/tree/v2.1-maintenance) ?

**Comment by phillipross** [comment]
@asifnaeem I see your confusion.  There is no longer a 1-to-1 relationship with the postgis-jdbc versions and PostGIS versions.  The 2.1.7.2 release of the postgis-jdbc extensions will work with all 2.1.x versions of PostGIS as well as earlier versions of PostGIS that are supported by the postgresql jdbc driver.  The 2.2.0 release of the postgis-jbc extensions will work with all 2.2.x versions of PostGIS as well as earlier releases (including 2.1.x).

@Elbehery that is correct... 2.2.x releases of the postgis-jdbc extensions will work on earlier versions of PostGIS.

**Comment by phillipross** [comment]
@asifnaeem The postgis-jdbc extensions project has been separated out of the core PostGIS project since last year.  There was a long period of time (several years) that the postgis-jdbc extensions were part of the PostGIS codebase, but it was not maintained due to lack of interest and expertise.  Since then, the postgis-jdbc extensions have been separated out and no longer follow precise versions of PostGIS.

The v2.1-maintenance branch only exists for legacy purposes, and should not be used unless a bugfix release of PostGIS 2.1 breaks compatibility with the latest version of postgis- extensions (which is unlikely to happen).

Currently, the master branch of the postgis-jdbc extensions should support all PostGIS versions that are supported by the postgresql jdbc driver.  If you're bumping into some problems in the 2.2.x codeline of the postgis-jdbc, we can troubleshoot those and fix any bugs that we might find in the 2.2.x codeline.  Attempting to use an older release of the postgis-jdbc extensions is not likely to be a solution for any problems you might be encountering.

The example code you have been referring to is actually part of the test harness in the codebase, and is meant to be executed as part of a maven build.  Take care when referring to this code because there may be some faulty geometries that are used to verify that PostGIS properly throws an error when using faulty geometries.  Not all of the geometries defined in the code should be considered valid.

I hope this clears up some of the confusion! :smile:

**Comment by asifnaeem** [comment]
Sure. Thank you phillipross and Elbehery.

**Comment by asifnaeem** [comment]
Sure. Thank you phillipross and Elbehery, it is helpful.
