### ISSUE TITLE
Prepare result jars/maven modules for use in Java Platform Module System (JPMS).

### ISSUE THREAD

**Issue by AndreasWBartels** [postgis/postgis-java#84]
Hey,

Please prepare the result jars/maven modules postgres-jdbc and postgis-geometry for use in Java Platform Module System (JPMS).

With version 2.5.0 the jars are no longer usable in projects that JPMS use.

This was done with this step:
 [#79](https://github.com/postgis/postgis-java/pull/79) Decoupled geometry and encoder/decoder from postgres-jdbc
-   Introduced postgis-geometry module which now contain geometry classes, parser, and encoder/decoder

Because we have now to jars/JPMS modules, who use the same package path.

a) Migrate to JPMS modules or add Automatic-Module-Name
b) Solve shared package problem
c) may solve [#32](https://github.com/postgis/postgis-java/issues/32) repackage classes as net.postgis instead of org.postgis

**Comment by phillipross** [comment]
If I'm not mistaken, adding Automatic-Module-Name alone would not address the shared package issue.  The next major version will refactor code, packages, etc and use JPMS properly.

The current shared package issue arose from a short term requirement to decouple the postgis geometry and parsing from the postgis jdbc driver itself, but required backwards compatibilty.  The next major version will have the luxury of being able to break backward compatibility allowing much cleaner and more straightforward approach to organizing functionality, code, modules, artifacts, etc while targeting more modern JDKs.

**Comment by AndreasWBartels** [comment]
You are right with, adding Automatic-Module-Name alone would not address the shared package issue.

Solving the shared package issue. Is the main problem, to make 2.5.0 usable with JPMS.

Adding Automatic-Module-Name, is an alternative to support IDEs and build systems to build a stable classpath, 
if there is no plan to migrate the modules to JPMS modules.

"The next major version will have the luxury of being able to break backward compatibility", did this address Version 3.0.0?
Exists a release or time plan?

**Comment by phillipross** [comment]
The next major version will be 3.x, yes.  And this next major version unfortunately has been stuck in the planning stages for quite awhile as there's a lot of things to consider.

The idea of a new module named postgis-jdbc-all for a 2.6.x release sounds like a workable idea.  It could probably be done without breaking compatibility and simply being a module that uses maven share plugin to combine the jdbc and geometry module contents into a single artifact.  Is this something you'd be capable and willing to help with?  Contributions would be very welcome!

**Comment by soc** [comment]
@phillipross I'm wondering – would it make sense to bundle the fix of this issue plus the package rename (#32) into a new major version, instead of trying to fix this in a possibly more compatibility-endangering changes in 2.x?

(My thinking is that the package rename is a breaking change anyway, so whatever change is necessary to resolve this issue might not add too much pain on top of that.)

... and then "this next major version unfortunately has been stuck in the planning stages for quite awhile" could be 4.x?

If you think this makes sense, I'm happy to look into #32/#84.

**Comment by phillipross** [comment]
@soc it does make sense, and I'd already begun to formulate things this way, but every week I keep getting stalled by unrelated projects 😆 

One other thing that I was planning for the next major release was to NOT continue with the major release number as 3, but of something else... maybe the year 2020 or something.  While I'm not completely sure of the implications of time-based releases, I wanted to get away from the confusion that release v2 was for postgis v2, and upcoming v3 would be postgis v3.  The major version numbers are not meant to coincide with the postgis release numbers at all, but many people mistakenly assume that the major version numbers imply compatibility.  The postgres jdbc driver ran into this issue and chose to increment the major release version to some arbitrary number and chose v42 (ala hitchhikers guide to the galaxy) but didn't take into account that the number 42 also happen to coincide with a jdbc specification version and now some mistakenly assume the 42.x jdbc drivers support jdbc v4.2 🤣

I was thinking changing the major version number to the current year would be harmless enough while fulfilling the goals.  Any thoughts on this?

**Comment by soc** [comment]
Interesting idea – I think you would still need some kind of version particle that indicates the targeted postgis version.

Also, having time-based versions would really mess with Maven plugins that check your Maven dependencies for newer versions, because these tools don't understand the versioning scheme.

But I guess that's the same with the "normal" versioning – if the tools saw 2.6 (targeted at postgis 2) and 3.2 (targeted at postgis 3), it would list 3.2 as the "latest" version, even the current version was e. g. 2.4.

**Comment by phillipross** [comment]
That's correct.  I figured all of this would be solved by totally decoupling the postgis java release version from the postgis supported version.  As it stands right now, postgis-java is very compatible with even the oldest pre 1.0 postgis releases and older unsupported versions of Postgres.  There's even more backwards compatibility maintained than the postgres jdbc driver itself.  Decoupling the postgis-java artifact versions from the postgis release versions or any other versions of anything is really the way to go.  Well-maintained documentation with support matrices mentioning postgres versions, postgis versions, postgis-java versions, and other affiliated projects can bridge the gap.

**Comment by soc** [comment]
Sounds good! The only question remaining is how to distinguish major releases from minor ones with a date-based versioning scheme.

Apart from that, do you have any big plans for 2.x that would be painful to keep in sync, if there was a new branch that did the renaming and the Java module system fixesß

**Comment by phillipross** [comment]
> Sounds good! The only question remaining is how to distinguish major releases from minor ones with a date-based versioning scheme.

Something that seems to work for other projects is to break out of strict semantic versioning scheme and do a YEAR.MAJOR.MINOR.PATCH versioning scheme.

> Apart from that, do you have any big plans for 2.x that would be painful to keep in sync, if there was a new branch that did the renaming and the Java module system fixes?

There were basically no plans for v2.x.  There are a few unfiled issues pertaining to road map that I had floating around outside of github, but I've not had time to marshal them into github issues or any kind of roadmap that would make sense.  The requirement to make postgis-java work with JPMS projects came up and my idea of a separate maven module that would transform the existing modules via maven-shade-plugin was just an idea that would maintain compatibility (for existing modules) and provide a way to get the package sharing out of the mix so minimal JPMS could be utilized.  Other than that, there were no real plans for current v2.

**Comment by soc** [comment]
> YEAR.MAJOR.MINOR.PATCH versioning scheme

But wouldn't you then have the same issue with the major version being misinterpreted as before?

**Comment by phillipross** [comment]
I would say there's much less chance of confusion if the leading number is easily recognized as corresponding to a year.  The "major version" would restart at 1 again every year, and maybe shouldn't be called "major version" any more since it's not so major anymore if it's preceded by the year.  It's only major in that it would indicate that there may be breaking changes.  Of course, this is also something that can be spelled out within documentation, but adding the year to the version scheme seems to be a low-cost way to add an extra indicator in there that the version numbers do not correspond to postgres version.

**Comment by soc** [comment]
@phillipross https://github.com/postgis/postgis-java/pull/85.

**Comment by soc** [comment]
This should be fixed in the upcoming 2020-series releases!

**Comment by soc** [comment]
This could be closed (https://github.com/postgis/postgis-java/issues/32 too), right?

That only leaves one issue in the existing milestone ... what's the chance to get a release out?
